
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0  # Use the latest version
    hooks:
      - id: commitizen
        args: ["--commit-msg-file"]
        stages: [commit-msg]  # Validates at the commit-msg stage

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        entry: poetry run pylint
        language: system
        args: ["--rcfile=.pylintrc", "--load-plugins=pylint_django", "."]
        pass_filenames: false
        always_run: true
        fail_fast: true


    
