repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0  # Use the latest version
    hooks:
      - id: commitizen
        args: ["--commit-msg-file"]
        stages: [commit-msg]  # Validates at the commit-msg stage

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5  # Use a valid version (check the latest release)
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]

