services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - network-matrix


  postgres:
    image: postgres:latest
    hostname: postgres-server
    container_name: postgres-matrix
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network-matrix

  redis:
    image: redis:latest
    hostname: redis-server
    container_name: redis-matrix
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - network-matrix

networks:
  network-matrix:
    name: network-matrix  # Custom name for the network
    driver: bridge

volumes:
  postgres_data:
  redis_data:
