services:
  postgres:
    image: postgres:latest
    hostname: postgres-server  
    container_name: postgres-matrix
    restart: always
    environment:
      POSTGRES_USER: matrix  
      POSTGRES_PASSWORD: 1JRwR35N6rHbpms7  
      POSTGRES_DB: matrix-meta  
    ports:
      - "5432:5432"  
    networks:
      - network-matrix

  redis:
    image: redis:latest
    hostname: redis-server
    container_name: redis-chat
    ports:
      - "6379:6379"
    networks:
      - network-matrix

networks:
  network-matrix:
    name: network-matrix  # Custom name for the network
    driver: bridge
