version: '3.9'

services:

  postgres:
    image: postgres:latest
    hostname: localhost  
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: django_user  
      POSTGRES_PASSWORD: django_password  
      POSTGRES_DB: django_db  
    ports:
      - "5432:5432"  

  redis:
    hostname: redis-server
    container_name: redis-chat
    image: redis:latest
    ports:
      - "6379:6379"
